name: test
on:
  push:
  pull_request:
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: codecov/codecov-action@v2
        with:
          files: ./coverage.info
          verbose: true
